on:
  push:
    branches:
      - testing

name: Console
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Commit
        run: |
          git status
          echo ${{ github.event }}
