on:
  push:
    branches:
      - master

name: "Testing D"

jobs:
  test_the_action:
    name: Test the action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: Angelk90/actions-download-file@master
        id: downloadfile
        name: Download a file
        with:
          url: '["https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/T._rex_infection.png/440px-T._rex_infection.png", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Mosasaurus-Skelett.jpg/440px-Mosasaurus-Skelett.jpg"]'
          target: public/
