on:
  push:
    branches:
      - testing

name: "Testing"
jobs:
  test_the_action:
    name: Test the action
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
      - uses: actions/checkout@v2
      - uses: angelk90/actions-download-file@master
        id: downloadfile
        name: Download a file
        with:
          url: "[API Endpoint](https://api.github.com/repos/suisei-cn/actions-download-file)"
          target: public/
          auto-match: true

      - name: Console
        run: echo "$GITHUB_CONTEXT"
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Display the file
        run: head -n8 public/actions-download-file
